import { lessonData } from './mockLessonData';

export const sampleStudent = [
  {
    cohort: 'A',
    emailAddress: 'classicalmoser@gmail.com',
    isAdmin: false,
    name: 'Student B',
    recordId: 2,
    relatedProgram: 3,
    role: 'student',
  },
];

export const sampleLessons = lessonData;

export const sampleActiveExamples = [];

export const sampleUserList = sampleStudent;

export const samplePrograms = [
  {
    cohortACurrentLesson: 124,
    cohortBCurrentLesson: 79,
    cohortCCurrentLesson: 250,
    cohortDCurrentLesson: 39,
    cohortECurrentLesson: 7,
    name: 'LearnCraft Spanish',
    recordId: 2,
    lessons: [sampleLessons.filter((lesson) => lesson.relatedProgram === 2)],
  },
  {
    cohortACurrentLesson: 1,
    cohortBCurrentLesson: 1,
    cohortCCurrentLesson: 1,
    cohortDCurrentLesson: 1,
    cohortECurrentLesson: null,
    name: 'SI1M',
    recordId: 3,
    lessons: [sampleLessons.filter((lesson) => lesson.relatedProgram === 3)],
  },
  {
    cohortACurrentLesson: 1,
    cohortBCurrentLesson: 1,
    cohortCCurrentLesson: 1,
    cohortDCurrentLesson: 1,
    cohortECurrentLesson: null,
    name: 'Ser Estar Mini Course',
    recordId: 4,
    lessons: [sampleLessons.filter((lesson) => lesson.relatedProgram === 4)],
  },
];

export const sampleMyExamples = {
  studentExamples: [
    {
      recordId: 112374,
      lastReviewedDate: '',
      nextReviewDate: '',
      reviewInterval: null,
      relatedStudent: 2,
      relatedExample: 8508,
      dateCreated: '2024-01-15T19:45:49Z',
      studentEmailAddress: 'classicalmoser@gmail.com',
    },
    {
      recordId: 112375,
      lastReviewedDate: '',
      nextReviewDate: '',
      reviewInterval: null,
      relatedStudent: 2,
      relatedExample: 8534,
      dateCreated: '2024-01-15T19:45:50Z',
      studentEmailAddress: 'classicalmoser@gmail.com',
    },
    {
      recordId: 112380,
      lastReviewedDate: '',
      nextReviewDate: '',
      reviewInterval: null,
      relatedStudent: 2,
      relatedExample: 3962,
      dateCreated: '2024-01-15T19:45:54Z',
      studentEmailAddress: 'classicalmoser@gmail.com',
    },
    {
      recordId: 112381,
      lastReviewedDate: '',
      nextReviewDate: '',
      reviewInterval: null,
      relatedStudent: 2,
      relatedExample: 2877,
      dateCreated: '2024-01-15T19:45:54Z',
      studentEmailAddress: 'classicalmoser@gmail.com',
    },
  ],
  examples: [
    {
      recordId: 2877,
      spanishExample: 'Hemos sido buenas amigas.',
      englishTranslation: 'We have been good friends(f).',
      vocabIncluded: [
        'amiga/Noun, Noun/',
        'buena/Adjective, Ser, positive/negative/',
        'hemos/Verb, Verb/standard (haber + participle)//1st person plural "nosotros" ; Present indicative',
        'sido/Verb, Verb/ser participle/',
      ],
      spanglish: 'esp',
      allStudents: [
        '1148',
        '1308',
        '1344',
        '1390',
        '1496',
        '1571',
        '1597',
        '1626',
        '194',
        '2',
        '210',
        '2162',
        '2285',
        '2475',
        '280',
        '285',
        '380',
        '392',
        '395',
        '396',
        '429',
        '443',
        '468',
        '479',
        '530',
        '534',
        '62',
        '646',
      ],
      englishAudio: '',
      spanishAudioLa: '',
      vocabComplete: true,
    },
    {
      recordId: 3962,
      spanishExample: 'Está aquí porque la tiene.',
      englishTranslation: 'He’s here because he has it(f).',
      vocabIncluded: [
        'aquí/Adverb, Place, here/there/',
        'está/Verb, Verb/he/she/it is//3rd person singular "él/ella/eso" ; Present indicative',
        'la/Pronoun, Direct Object/direct object/',
        'porque/Conjunction, Subordinating, normal/"because"/',
        'tiene/Verb, Verb//3rd person singular "él/ella/eso" ; Present indicative',
      ],
      spanglish: 'esp',
      allStudents: [
        '146',
        '1496',
        '1571',
        '1597',
        '171',
        '194',
        '2',
        '2162',
        '2283',
        '2475',
        '2551',
        '392',
        '443',
        '468',
        '530',
        '62',
        '787',
      ],
      englishAudio: '',
      spanishAudioLa: '',
      vocabComplete: true,
    },
    {
      recordId: 8508,
      spanishExample: '¡Buenos días! Gracias por ir conmigo.',
      englishTranslation: 'Good morning! Thank you for going with me.',
      vocabIncluded: [
        'buenos días/Cluster, Idiom/Greeting/',
        'conmigo/Pronoun, Prepositional/',
        'gracias/Interjection, Informational/',
        'ir/Verb, Verb//Infinitive',
        'por/Preposition, Preposition/"because of"/',
      ],
      spanglish: 'esp',
      allStudents: [
        '1148',
        '1390',
        '146',
        '1496',
        '1571',
        '1597',
        '1626',
        '1629',
        '194',
        '2',
        '2137',
        '2270',
        '2339',
        '2452',
        '2475',
        '2551',
        '2611',
        '342',
        '360',
        '392',
        '458',
        '468',
        '530',
      ],
      englishAudio:
        'https://dbexamples.s3.us-east-2.amazonaws.com/dbexamples/ex8508en.mp3',
      spanishAudioLa:
        'https://dbexamples.s3.us-east-2.amazonaws.com/dbexamples/ex8508la.mp3',
      vocabComplete: true,
    },
    {
      recordId: 8534,
      spanishExample: '¿Cómo vas a ir conmigo a ese lugar?',
      englishTranslation: 'How are you going to go with me to that place?',
      vocabIncluded: [
        'a/Preposition, Preposition/"to", indicating direction/movement/',
        'a/Preposition, Preposition/ir + a + infinitive (particle)/',
        'conmigo/Pronoun, Prepositional/',
        'cómo/Adverb, Manner, other/only in question, not exclamation/',
        'ese/Pronoun, Demonstrative/adjectival demonstrative/',
        'ir/Verb, Verb//Infinitive',
        'lugar/Noun, Noun/',
        'vas/Verb, Verb//2nd person singular "tú" ; 2nd person singular "vos" ; Present indicative',
      ],
      spanglish: 'esp',
      allStudents: [
        '1127',
        '1148',
        '1361',
        '1390',
        '146',
        '1467',
        '1496',
        '1571',
        '1597',
        '1710',
        '194',
        '2',
        '2137',
        '2162',
        '2283',
        '2339',
        '241',
        '2475',
        '2551',
        '360',
        '392',
        '438',
        '468',
        '530',
      ],
      englishAudio: '',
      spanishAudioLa: '',
      vocabComplete: true,
    },
  ],
};

export const sampleAudioExamples = sampleMyExamples.examples.filter(
  (item) => item.spanishAudioLa.length > 0,
);
