name: Setup pnpm
description: 'Installs Node.js and pnpm, and installs dependencies'
inputs:
  node-version:
    description: Node.js version to set up
    required: true
    default: 'lts/*'
runs:
  # eslint-disable-next-line yaml/plain-scalar
  using: "composite"
  steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          cache-node-modules-

    - name: Install dependencies
      run: pnpm install
