name: Continuous Integration

on:
  push:
    branches:
      - development
      - master
  # Allows manual deploy with CI
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Try to restore the cached mock data
      - name: Restore mock data cache
        uses: actions/cache@v2
        with:
          path: ./mocks/data/api/actualServerData.json
          key: mockdata-${{ hashFiles('./mocks/data/api/actualServerData.json') }}
          restore-keys: |
            mockdata-

      # Step 3: Conditionally install Node.js and fetch mock data if cache miss
      - name: Set up Node.js environment (only if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies (only if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Fetch mock data if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: node .github/workflows/update-cache.js

      # Step 4: Run the test suite (this runs regardless of cache hit or miss)
      - name: Run tests
        run: npm test
