name: Update Mock Data Cache Daily

on:
  # Runs daily at 8am UTC/2am CST
  schedule:
    - cron: '0 8 * * *'

  # Allows you to trigger the workflow manually
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run the update-cache.js script
      - name: Update Cache
        run: node .github/workflows/update-cache.ts
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}

      # Save the updated mock data to cache
      - name: Cache mock data
        uses: actions/cache@v2
        with:
          path: ./mocks/data/serverlike/actualServerData.json
          key: mockdata-${{ hashFiles('./src/functions/DataModel.ts, ./mocks/data/serverlike/serverlikeData.ts') }}
