name: Update Mock Data Cache Daily

on:
  # Runs daily at 8am UTC/2am CST
  schedule:
    - cron: "0 8 * * *"

  # Allows you to trigger the workflow manually
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js and all dependencies
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      # Step 4: Run the update-cache.js script
      - name: Update Cache
        run: node .github/workflows/update-cache.js
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}

      # Step 5: Save the updated mock data to cache
      - name: Cache mock data
        uses: actions/cache@v2
        with:
          path: ./mocks/data/serverlike/actualServerData.json
          key: mockdata-${{ hashFiles('./src/functions/DataModel.ts, ./mocks/data/serverlike/serverlikeData.ts') }}
